"""JSON line protocol helpers for the Isaac bridge sidecar."""

from __future__ import annotations

import json
from typing import Any


class ProtocolError(Exception):
    """Raised when request framing or payload shape is invalid."""

    def __init__(self, code: str, message: str, *, request_id: str | None = None) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        # Echoed back when the token survived parsing (contract §1).
        self.request_id = request_id


def parse_request_envelope(line: bytes | str) -> tuple[str, dict[str, Any], str | None]:
    """Decode one newline-delimited request into ``(cmd, args, request_id)``.

    ``request_id`` is an opaque client token (Engine Integration Contract v1
    §1).  It is echoed verbatim on the response when present and omitted
    entirely when absent — never parsed or generated by the bridge.
    """
    if isinstance(line, bytes):
        payload = line.decode("utf-8")
    else:
        payload = line
    payload = payload.strip()
    if not payload:
        raise ProtocolError("INVALID_REQUEST", "Empty request line")
    try:
        obj = json.loads(payload)
    except json.JSONDecodeError as exc:
        raise ProtocolError("INVALID_JSON", f"Malformed JSON: {exc}") from exc
    if not isinstance(obj, dict):
        raise ProtocolError("INVALID_REQUEST", "Request must be a JSON object")
    raw_request_id = obj.get("request_id")
    request_id = raw_request_id if isinstance(raw_request_id, str) else None
    cmd = obj.get("cmd")
    if not isinstance(cmd, str) or not cmd.strip():
        raise ProtocolError(
            "INVALID_REQUEST",
            "Request field 'cmd' must be a non-empty string",
            request_id=request_id,
        )
    args = obj.get("args", {})
    if not isinstance(args, dict):
        raise ProtocolError(
            "INVALID_REQUEST",
            "Request field 'args' must be an object",
            request_id=request_id,
        )
    return cmd.strip(), args, request_id


def parse_request_line(line: bytes | str) -> tuple[str, dict[str, Any]]:
    """Decode one newline-delimited request into ``(cmd, args)``."""
    cmd, args, _ = parse_request_envelope(line)
    return cmd, args


def ok_response(result: Any, *, request_id: str | None = None) -> dict[str, Any]:
    """Build a success envelope."""
    response: dict[str, Any] = {"ok": True, "result": result}
    if request_id is not None:
        response["request_id"] = request_id
    return response


def error_response(
    code: str,
    message: str,
    *,
    details: dict[str, Any] | None = None,
    request_id: str | None = None,
) -> dict[str, Any]:
    """Build an error envelope."""
    err: dict[str, Any] = {"code": code, "message": message}
    if details:
        err["details"] = details
    response: dict[str, Any] = {"ok": False, "error": err}
    if request_id is not None:
        response["request_id"] = request_id
    return response


def encode_response(response: dict[str, Any]) -> bytes:
    """Serialize a response envelope to one newline-delimited JSON line."""
    return (json.dumps(response, separators=(",", ":"), sort_keys=True) + "\n").encode("utf-8")
