"""Field solver ABC, built-in solvers, and solver pack discovery.

Built-in solvers:
- CalculiXSolver — structural FEA (apt install calculix-ccx)
- ElmerSolver — thermal + EM (Phase 3, stub only)

Additional solvers can be installed as pip packages that register the
``solidmind.solver_packs`` entry point.
"""
from __future__ import annotations

import importlib.metadata
import logging
import os
import shutil
import subprocess
import tempfile
import time
from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any

from server.analysis_models import (
    AnalysisCheck,
    AnalysisSpec,
    AnalysisType,
    CheckStatus,
    FieldResult,
    MeshInfo,
    ScalarFieldSummary,
)

log = logging.getLogger("solidmind.analysis_solvers")

# ---------------------------------------------------------------------------
# ABC
# ---------------------------------------------------------------------------


class FieldSolver(ABC):
    """Base class for field-problem solvers (FEA, thermal, EM)."""

    @abstractmethod
    def name(self) -> str:
        """Unique solver identifier (e.g. 'calculix', 'elmer')."""

    @abstractmethod
    def analysis_types(self) -> list[AnalysisType]:
        """Which analysis types this solver supports."""

    @abstractmethod
    def available(self) -> tuple[bool, str]:
        """Check if the solver binary is installed.

        Returns (True, diagnostic) or (False, install_instructions).
        """

    @abstractmethod
    def write_input(
        self,
        spec: AnalysisSpec,
        mesh_info: MeshInfo,
        work_dir: Path,
    ) -> Path:
        """Write solver input files to *work_dir*.  Return the main input file path."""

    @abstractmethod
    def run(self, input_path: Path, work_dir: Path) -> float:
        """Execute the solver.  Return wall-clock time in seconds."""

    @abstractmethod
    def parse_results(
        self,
        work_dir: Path,
        spec: AnalysisSpec,
    ) -> FieldResult:
        """Parse solver output and return structured results."""

    def supports_direct_solve(self) -> bool:
        """Whether this solver supports direct in-process solve from assembled matrices."""
        return False

    def solve_direct(
        self,
        spec: AnalysisSpec,
        mesh_info: MeshInfo,
        work_dir: Path,
    ) -> FieldResult:
        """Optional in-process fast path for direct solvers."""
        raise NotImplementedError


# ---------------------------------------------------------------------------
# CalculiX solver
# ---------------------------------------------------------------------------


class CalculiXSolver(FieldSolver):
    """CalculiX (ccx) structural FEA solver."""

    def name(self) -> str:
        return "calculix"

    def analysis_types(self) -> list[AnalysisType]:
        return [AnalysisType.STRUCTURAL]

    def available(self) -> tuple[bool, str]:
        ccx = shutil.which("ccx")
        if ccx:
            return True, f"ccx found at {ccx}"
        return False, "ccx not found. Install with: apt install calculix-ccx"

    def write_input(
        self,
        spec: AnalysisSpec,
        mesh_info: MeshInfo,
        work_dir: Path,
    ) -> Path:
        """Generate CalculiX .inp file from spec and mesh.

        Reads the meshio-generated Abaqus .inp to discover actual set names,
        then writes a main .inp that references the correct sets.
        """
        mat = spec.material

        # Convert .msh → Abaqus .inp (nodes, elements, sets)
        mesh_inp_path = self._convert_mesh_to_inp(mesh_info, work_dir)

        # Parse the full meshio output for actual set names (mesh_full.inp)
        elset_names = self._parse_set_names(mesh_inp_path)

        # Build BC face group name → meshio elset name mapping
        bc_face_groups: dict[str, str] = {}
        for i, bc in enumerate(spec.boundary_conditions):
            group_name = f"bc_{i}_{bc.bc_type}"
            # meshio sanitises names — check exact and variants
            for candidate in [group_name, group_name.replace(".", "_")]:
                if candidate in elset_names:
                    bc_face_groups[group_name] = candidate
                    break

        # Find the volume element set
        vol_elset = "volume"
        if vol_elset not in elset_names:
            # Fallback: use the first C3D4 set or any set with "vol" in name
            for name in elset_names:
                if "vol" in name.lower():
                    vol_elset = name
                    break

        # Write the main analysis .inp
        inp_path = work_dir / "analysis.inp"
        lines: list[str] = []
        lines.append("** CalculiX input generated by SolidMind CAD")
        lines.append(f"** Body: {spec.body}")
        lines.append(f"** Material: {mat.name}")
        lines.append("")

        # Include mesh
        lines.append("*INCLUDE, INPUT=mesh.inp")
        lines.append("")

        # Collect valid node IDs (nodes used by C3D4 volume elements)
        ccx_mesh = work_dir / "mesh.inp"
        valid_nodes = self._collect_volume_node_ids(ccx_mesh)

        # Generate explicit node sets from surface element sets for BCs
        nset_node_counts: dict[str, int] = {}
        for i, bc in enumerate(spec.boundary_conditions):
            group_name = f"bc_{i}_{bc.bc_type}"
            elset = bc_face_groups.get(group_name)
            if elset:
                nset_name = f"Nbc{i}"
                node_ids = self._extract_nset_from_elset(mesh_inp_path, elset)
                # Filter to only nodes that exist in the volume mesh
                if valid_nodes:
                    node_ids = [n for n in node_ids if n in valid_nodes]
                if node_ids:
                    lines.append(f"*NSET, NSET={nset_name}")
                    for j in range(0, len(node_ids), 8):
                        chunk = node_ids[j:j + 8]
                        lines.append(", ".join(str(n) for n in chunk))
                    lines.append("")
                nset_node_counts[nset_name] = len(node_ids)

        # Material definition — CalculiX uses mm/N/MPa consistent units
        lines.append(f"*MATERIAL, NAME={mat.name.upper()}")
        lines.append("*ELASTIC")
        lines.append(f"{mat.youngs_modulus_mpa}, {mat.poissons_ratio}")
        lines.append("*DENSITY")
        density_tonne_mm3 = mat.density_kg_m3 * 1e-12
        lines.append(f"{density_tonne_mm3:.6e}")
        lines.append("")

        # Assign material to volume elements
        lines.append(f"*SOLID SECTION, ELSET={vol_elset}, MATERIAL={mat.name.upper()}")
        lines.append("")

        # Boundary conditions
        lines.append("*STEP")
        lines.append("*STATIC")
        lines.append("")

        for i, bc in enumerate(spec.boundary_conditions):
            nset_name = f"Nbc{i}"
            group_name = f"bc_{i}_{bc.bc_type}"
            has_set = group_name in bc_face_groups

            if not has_set:
                lines.append(f"** WARNING: no element set found for BC {i} ({bc.bc_type})")
                lines.append("")
                continue

            if bc.bc_type == "fixed":
                lines.append(f"** BC {i}: fixed")
                lines.append(f"*BOUNDARY")
                lines.append(f"{nset_name}, 1, 3, 0.0")
            elif bc.bc_type == "force":
                lines.append(f"** BC {i}: force")
                lines.append(f"*CLOAD")
                # Load contract: force values are total force on the face set.
                # CalculiX CLOAD on an NSET applies value per node, so we divide.
                node_count = max(nset_node_counts.get(nset_name, 0), 1)
                fx = bc.value.get("fx", 0.0) / node_count
                fy = bc.value.get("fy", 0.0) / node_count
                fz = bc.value.get("fz", 0.0) / node_count
                if fx != 0:
                    lines.append(f"{nset_name}, 1, {fx}")
                if fy != 0:
                    lines.append(f"{nset_name}, 2, {fy}")
                if fz != 0:
                    lines.append(f"{nset_name}, 3, {fz}")
            elif bc.bc_type == "pressure":
                p = bc.value.get("pressure_mpa", 0.0)
                elset = bc_face_groups[group_name]
                lines.append(f"** BC {i}: pressure")
                lines.append(f"*DLOAD")
                lines.append(f"{elset}, P, {p}")
            lines.append("")

        # Output requests
        lines.append("*NODE FILE")
        lines.append("U")
        lines.append("*EL FILE")
        lines.append("S")
        lines.append("*END STEP")

        inp_path.write_text("\n".join(lines))
        return inp_path

    def _convert_mesh_to_inp(self, mesh_info: MeshInfo, work_dir: Path) -> Path:
        """Convert Gmsh .msh to CalculiX-compatible .inp format.

        Uses meshio to read the Gmsh mesh, then writes a CalculiX-native .inp
        with proper formatting (CalculiX is picky about field widths).
        Also writes the meshio Abaqus output for BC set name extraction.
        """
        full_inp = work_dir / "mesh_full.inp"
        mesh_inp = work_dir / "mesh.inp"
        try:
            import meshio
            mesh = meshio.read(mesh_info.path)
            # Write meshio Abaqus for set name parsing
            meshio.write(str(full_inp), mesh, file_format="abaqus")
            # Write CalculiX-native .inp
            self._write_ccx_native(mesh, mesh_inp)
        except ImportError:
            log.warning("meshio not installed, writing stub mesh.inp")
            mesh_inp.write_text("** meshio not available\n")
            full_inp.write_text("** meshio not available\n")
        except Exception as exc:
            log.warning("Mesh conversion failed: %s", exc)
            mesh_inp.write_text(f"** mesh conversion failed: {exc}\n")
            full_inp.write_text(f"** mesh conversion failed: {exc}\n")
        return full_inp  # return full for set parsing

    def _write_ccx_native(self, mesh: Any, out_path: Path) -> None:
        """Write a CalculiX-compatible .inp directly from meshio mesh object.

        Only includes volume elements (tetra) and all nodes.
        Uses free-format with proper spacing that CalculiX can parse.
        """
        import numpy as np

        lines: list[str] = []
        lines.append("** CalculiX mesh written by SolidMind CAD")

        # Nodes — CalculiX free format: id, x, y, z
        # CalculiX has a 132-character line limit; keep coords ≤ 20 chars each
        lines.append("*NODE, NSET=Nall")
        points = mesh.points
        for i, (x, y, z) in enumerate(points):
            nid = i + 1  # 1-based
            lines.append(f"{nid}, {x:.10g}, {y:.10g}, {z:.10g}")

        # Elements — only volume (tetra4)
        tet_cells = []
        elem_id = 1
        for cell_block in mesh.cells:
            if cell_block.type == "tetra":
                lines.append(f"*ELEMENT, TYPE=C3D4, ELSET=volume")
                for conn in cell_block.data:
                    nodes = ", ".join(str(int(n) + 1) for n in conn)  # 1-based
                    lines.append(f"{elem_id}, {nodes}")
                    elem_id += 1

        out_path.write_text("\n".join(lines) + "\n")

    def _parse_set_names(self, inp_path: Path) -> set[str]:
        """Parse *ELSET and *NSET names from a meshio-generated .inp."""
        names: set[str] = set()
        try:
            for line in inp_path.read_text().splitlines():
                upper = line.upper().strip()
                if upper.startswith("*ELSET") or upper.startswith("*NSET"):
                    for part in line.split(","):
                        part = part.strip()
                        if part.upper().startswith("ELSET=") or part.upper().startswith("NSET="):
                            name = part.split("=", 1)[1].strip()
                            names.add(name)
        except Exception:
            pass
        return names

    def _collect_volume_node_ids(self, ccx_inp: Path) -> set[int]:
        """Collect all node IDs referenced by C3D4 elements in the filtered mesh."""
        node_ids: set[int] = set()
        try:
            in_c3d4 = False
            for line in ccx_inp.read_text().splitlines():
                stripped = line.strip()
                upper = stripped.upper()
                if upper.startswith("*ELEMENT") and "TYPE=C3D4" in upper:
                    in_c3d4 = True
                    continue
                if in_c3d4 and stripped.startswith("*"):
                    in_c3d4 = False
                    continue
                if in_c3d4:
                    parts = [p.strip() for p in stripped.rstrip(",").split(",") if p.strip()]
                    # parts[0] = element ID, parts[1:] = node IDs
                    for p in parts[1:]:
                        try:
                            node_ids.add(int(p))
                        except ValueError:
                            pass
        except Exception:
            pass
        return node_ids

    def _extract_nset_from_elset(
        self,
        inp_path: Path,
        elset_name: str,
    ) -> list[int]:
        """Extract unique node IDs from a surface element set in a meshio .inp.

        Reads the *ELSET to get element IDs, then finds those elements
        in *ELEMENT blocks to collect node IDs.
        """
        text = inp_path.read_text()
        lines = text.splitlines()

        # 1. Collect element IDs from the named ELSET
        elem_ids: set[int] = set()
        in_target = False
        for line in lines:
            stripped = line.strip()
            if stripped.upper().startswith("*ELSET") and f"ELSET={elset_name}" in stripped:
                in_target = True
                continue
            if in_target:
                if stripped.startswith("*"):
                    in_target = False
                    continue
                for tok in stripped.rstrip(",").split(","):
                    tok = tok.strip()
                    if tok.isdigit():
                        elem_ids.add(int(tok))

        if not elem_ids:
            return []

        # 2. Find nodes for those elements in *ELEMENT blocks
        node_ids: set[int] = set()
        in_element = False
        for line in lines:
            stripped = line.strip()
            if stripped.upper().startswith("*ELEMENT"):
                in_element = True
                continue
            if in_element:
                if stripped.startswith("*"):
                    in_element = False
                    continue
                parts = [p.strip() for p in stripped.rstrip(",").split(",") if p.strip()]
                if not parts:
                    continue
                try:
                    eid = int(parts[0])
                except ValueError:
                    continue
                if eid in elem_ids:
                    for p in parts[1:]:
                        try:
                            node_ids.add(int(p))
                        except ValueError:
                            pass

        return sorted(node_ids)

    def run(self, input_path: Path, work_dir: Path) -> float:
        """Run ccx solver."""
        job_name = input_path.stem
        t0 = time.monotonic()
        result = subprocess.run(
            ["ccx", "-i", job_name],
            cwd=str(work_dir),
            capture_output=True,
            text=True,
            timeout=300,
        )
        elapsed = time.monotonic() - t0

        if result.returncode != 0:
            log.error("ccx failed (rc=%d): %s", result.returncode, result.stderr)
            raise RuntimeError(
                f"CalculiX failed (rc={result.returncode}): {result.stderr[:500]}"
            )

        return elapsed

    def parse_results(
        self,
        work_dir: Path,
        spec: AnalysisSpec,
    ) -> FieldResult:
        """Parse CalculiX .frd output."""
        from server.analysis_result_parser import parse_frd

        frd_path = work_dir / "analysis.frd"
        if not frd_path.exists():
            return _failed_result(
                "No .frd output file found — solver may have failed",
                spec,
            )

        return parse_frd(frd_path, spec)


# ---------------------------------------------------------------------------
# Mock solver for testing
# ---------------------------------------------------------------------------


class MockFieldSolver(FieldSolver):
    """Deterministic mock solver for tests.  No external dependencies."""

    def __init__(self, *, fail: bool = False) -> None:
        self._fail = fail

    def name(self) -> str:
        return "mock"

    def analysis_types(self) -> list[AnalysisType]:
        return [AnalysisType.STRUCTURAL, AnalysisType.THERMAL]

    def available(self) -> tuple[bool, str]:
        return True, "mock solver (always available)"

    def write_input(
        self,
        spec: AnalysisSpec,
        mesh_info: MeshInfo,
        work_dir: Path,
    ) -> Path:
        p = work_dir / "mock.inp"
        p.write_text("mock input\n")
        return p

    def run(self, input_path: Path, work_dir: Path) -> float:
        if self._fail:
            raise RuntimeError("Mock solver failure")
        # Write mock output
        (work_dir / "mock.out").write_text("mock output\n")
        return 0.01

    def parse_results(
        self,
        work_dir: Path,
        spec: AnalysisSpec,
    ) -> FieldResult:
        if spec.analysis_type == AnalysisType.THERMAL:
            return self._mock_thermal_result(spec)
        return self._mock_structural_result(spec)

    def _mock_structural_result(self, spec: AnalysisSpec) -> FieldResult:
        yield_mpa = spec.material.yield_strength_mpa
        max_stress = yield_mpa * 0.6  # 60% of yield → safe
        safety_factor = yield_mpa / max_stress if max_stress > 0 else 99.0

        checks = [
            AnalysisCheck(
                name="yield_check",
                status=CheckStatus.PASS,
                message=f"Max von Mises {max_stress:.1f} MPa < yield {yield_mpa:.1f} MPa",
                measured=max_stress,
                limit=yield_mpa,
                suggestion="",
            ),
        ]

        fields = [
            ScalarFieldSummary(
                field_name="von_mises_stress",
                min_val=0.0,
                max_val=max_stress,
                mean_val=max_stress * 0.3,
                unit="MPa",
                max_location_xyz=(10.0, 5.0, 0.0),
            ),
            ScalarFieldSummary(
                field_name="displacement",
                min_val=0.0,
                max_val=0.05,
                mean_val=0.02,
                unit="mm",
                max_location_xyz=(20.0, 10.0, 0.0),
            ),
        ]

        return FieldResult(
            analysis_id="mock_001",
            status=CheckStatus.PASS,
            safety_factor=round(safety_factor, 2),
            max_von_mises_mpa=round(max_stress, 2),
            max_displacement_mm=0.05,
            checks=tuple(checks),
            scalar_fields=tuple(fields),
            solver_name="mock",
            solve_time_s=0.01,
        )

    def _mock_thermal_result(self, spec: AnalysisSpec) -> FieldResult:
        """Generate plausible mock thermal result."""
        # Extract temperature BCs to make the result plausible
        t_values: list[float] = []
        max_temp_limit = 0.0
        for bc in spec.boundary_conditions:
            if bc.bc_type == "temperature":
                t_values.append(bc.value.get("temperature_k", 293.15))
            limit = bc.value.get("max_temperature_k", 0.0)
            if limit > 0:
                max_temp_limit = max(max_temp_limit, limit)

        if len(t_values) >= 2:
            t_min = min(t_values)
            t_max = max(t_values)
        elif t_values:
            t_min = t_values[0]
            t_max = t_values[0] + 50.0
        else:
            t_min = 293.15
            t_max = 373.15

        t_mean = (t_min + t_max) / 2.0
        safety_factor = max_temp_limit / t_max if max_temp_limit > 0 and t_max > 0 else 99.0

        checks = [
            AnalysisCheck(
                name="thermal_gradient",
                status=CheckStatus.PASS,
                message=(
                    f"Thermal gradient {t_max - t_min:.1f} K "
                    f"(from {t_min:.1f} K to {t_max:.1f} K)"
                ),
                measured=t_max - t_min,
            ),
        ]
        if max_temp_limit > 0:
            status = CheckStatus.PASS if t_max <= max_temp_limit else CheckStatus.FAIL
            checks.insert(0, AnalysisCheck(
                name="overtemperature",
                status=status,
                message=(
                    f"Max temperature {t_max:.1f} K vs limit {max_temp_limit:.1f} K"
                ),
                measured=t_max,
                limit=max_temp_limit,
            ))

        fields = [
            ScalarFieldSummary(
                field_name="temperature",
                min_val=round(t_min, 2),
                max_val=round(t_max, 2),
                mean_val=round(t_mean, 2),
                unit="K",
                max_location_xyz=(10.0, 5.0, 0.0),
            ),
        ]

        overall = CheckStatus.PASS
        if any(c.status == CheckStatus.FAIL for c in checks):
            overall = CheckStatus.FAIL
        elif any(c.status == CheckStatus.WARN for c in checks):
            overall = CheckStatus.WARN

        return FieldResult(
            analysis_id="mock_thermal_001",
            status=overall,
            safety_factor=round(safety_factor, 2),
            max_von_mises_mpa=0.0,
            max_displacement_mm=0.0,
            checks=tuple(checks),
            scalar_fields=tuple(fields),
            solver_name="mock",
            solve_time_s=0.01,
        )


# ---------------------------------------------------------------------------
# Solver registry
# ---------------------------------------------------------------------------

FIELD_SOLVERS: dict[str, FieldSolver] = {}


def register_solver(solver: FieldSolver) -> None:
    """Register a field solver.  Warns on duplicate name."""
    if solver.name() in FIELD_SOLVERS:
        log.warning("Duplicate solver name %r, skipping", solver.name())
        return
    FIELD_SOLVERS[solver.name()] = solver
    log.info("Registered field solver: %s", solver.name())


def get_solver(
    solver_name: str = "",
    analysis_type: AnalysisType = AnalysisType.STRUCTURAL,
    dof_count: int | None = None,
) -> FieldSolver | None:
    """Get a solver by name, or auto-select the first available for the type."""
    if solver_name:
        return FIELD_SOLVERS.get(solver_name)

    if analysis_type == AnalysisType.STRUCTURAL and dof_count is not None:
        cudss_min = _env_int("SOLIDMIND_CUDSS_DOF_MIN", 200_000)
        cholmod_min = _env_int("SOLIDMIND_CHOLMOD_DOF_MIN", 5_000)

        preferred_names: list[str]
        if dof_count >= cudss_min:
            preferred_names = ["cudss", "cholmod", "calculix"]
        elif dof_count >= cholmod_min:
            preferred_names = ["cholmod", "calculix"]
        else:
            preferred_names = ["calculix"]

        for name in preferred_names:
            solver = FIELD_SOLVERS.get(name)
            if solver is None:
                continue
            if analysis_type not in solver.analysis_types():
                continue
            ok, _ = solver.available()
            if ok:
                return solver

    # Auto-select: first available solver that supports the analysis type
    for solver in FIELD_SOLVERS.values():
        if analysis_type in solver.analysis_types():
            ok, _ = solver.available()
            if ok:
                return solver

    return None


def list_solvers() -> list[dict[str, Any]]:
    """List all registered solvers with availability status."""
    result: list[dict[str, Any]] = []
    for solver in FIELD_SOLVERS.values():
        ok, msg = solver.available()
        result.append({
            "name": solver.name(),
            "analysis_types": [t.value for t in solver.analysis_types()],
            "available": ok,
            "diagnostic": msg,
            "supports_direct_solve": solver.supports_direct_solve(),
        })
    return result


def _env_int(name: str, default: int) -> int:
    raw = os.environ.get(name)
    if raw is None:
        return default
    try:
        return int(raw)
    except ValueError:
        log.warning("Invalid %s=%r, using default %d", name, raw, default)
        return default


# ---------------------------------------------------------------------------
# Solver pack discovery
# ---------------------------------------------------------------------------


def _discover_solver_packs() -> None:
    """Load solver packs from ``solidmind.solver_packs`` entry points."""
    for ep in importlib.metadata.entry_points(group="solidmind.solver_packs"):
        try:
            mod = ep.load()
            solvers = getattr(mod, "SOLVERS", [])
            for solver in solvers:
                register_solver(solver)
            log.info(
                "Loaded solver pack %r: %d solvers", ep.name, len(solvers),
            )
        except Exception:
            log.exception("Failed to load solver pack %r", ep.name)


# ---------------------------------------------------------------------------
# Register built-in solvers
# ---------------------------------------------------------------------------

register_solver(CalculiXSolver())
register_solver(MockFieldSolver())

# Optional in-process direct structural solvers
try:
    from server.analysis_solver_cholmod import CHOLMODSolver  # noqa: E402
    register_solver(CHOLMODSolver())
except Exception:
    log.warning("CHOLMOD solver registration skipped", exc_info=True)

try:
    from server.analysis_solver_cudss import CuDSSSolver  # noqa: E402
    register_solver(CuDSSSolver())
except Exception:
    log.warning("cuDSS solver registration skipped", exc_info=True)

# Elmer thermal solver
try:
    from server.analysis_solver_elmer import ElmerSolver  # noqa: E402
    register_solver(ElmerSolver())
except Exception:
    log.debug("Elmer solver not available", exc_info=True)

# Aerodynamic solvers
from server.analysis_solver_su2 import SU2Solver  # noqa: E402
from server.analysis_solver_dust import DUSTSolver, MockDUSTSolver  # noqa: E402

register_solver(SU2Solver())
register_solver(DUSTSolver())
register_solver(MockDUSTSolver())

# Discover packs at import time (same pattern as tool packs)
_discover_solver_packs()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _failed_result(message: str, spec: AnalysisSpec) -> FieldResult:
    return FieldResult(
        analysis_id="",
        status=CheckStatus.FAIL,
        safety_factor=0.0,
        max_von_mises_mpa=0.0,
        max_displacement_mm=0.0,
        checks=(
            AnalysisCheck(
                name="solver_error",
                status=CheckStatus.FAIL,
                message=message,
                suggestion="Check solver installation and input files",
            ),
        ),
        scalar_fields=(),
        solver_name="",
    )
