"""SU2 CFD solver adapter for aerodynamic analysis.

SU2 (Stanford University Unstructured) is an open-source CFD suite for
aerodynamic analysis and shape optimization.  It uses RANS equations with
various turbulence models for external aerodynamics.

Binary: ``SU2_CFD`` (main solver).  Install via package manager or from source:
  - Ubuntu: ``sudo apt install su2``
  - Conda: ``conda install -c conda-forge su2``
  - Source: https://su2code.github.io/

Mesh flow: STEP → Gmsh (.msh) → SU2 format (.su2) via meshio.
"""

from __future__ import annotations

import csv
import logging
import shutil
import subprocess
import time
from pathlib import Path

from server.analysis_models import (
    AeroReference,
    AeroResult,
    AnalysisCheck,
    AnalysisSpec,
    AnalysisType,
    CheckStatus,
    FieldResult,
    FlowConditions,
    MeshInfo,
    ScalarFieldSummary,
)
from server.analysis_solvers import FieldSolver

log = logging.getLogger("solidmind.solver_su2")


class SU2Solver(FieldSolver):
    """SU2 RANS CFD solver for external aerodynamics."""

    def name(self) -> str:
        return "su2"

    def analysis_types(self) -> list[AnalysisType]:
        return [AnalysisType.AERODYNAMIC, AnalysisType.HYDRODYNAMIC]

    def available(self) -> tuple[bool, str]:
        binary = shutil.which("SU2_CFD")
        if binary:
            return True, f"SU2_CFD found at {binary}"
        return False, (
            "SU2_CFD not found. Install with:\n"
            "  apt install su2  (Ubuntu)\n"
            "  conda install -c conda-forge su2  (Conda)\n"
            "  https://su2code.github.io/ (source)"
        )

    def write_input(
        self,
        spec: AnalysisSpec,
        mesh_info: MeshInfo,
        work_dir: Path,
    ) -> Path:
        """Generate SU2 .cfg and convert mesh to .su2 format."""
        cfg_path = work_dir / "config.cfg"

        # Convert mesh to SU2 format
        su2_mesh_path = work_dir / "mesh.su2"
        self._convert_mesh_to_su2(mesh_info.path, str(su2_mesh_path))

        # Extract flow conditions from spec boundary conditions
        flow = self._extract_flow_conditions(spec)
        ref = self._extract_aero_reference(spec)

        # Compute Reynolds number
        re = (flow.density_kg_m3 * flow.velocity_m_s * ref.chord_m) / flow.viscosity_pa_s
        mach = flow.mach
        if mach <= 0:
            # Speed of sound at ISA sea level ≈ 340.3 m/s
            mach = flow.velocity_m_s / 340.3

        lines: list[str] = []
        lines.append("% SU2 configuration generated by SolidMind CAD")
        lines.append(f"% Body: {spec.body}")
        lines.append("")

        # Problem definition
        if mach < 0.3:
            lines.append("SOLVER= INC_RANS")
            lines.append("KIND_TURB_MODEL= SA")
            lines.append("INC_DENSITY_MODEL= CONSTANT")
            lines.append(f"INC_DENSITY_INIT= {flow.density_kg_m3}")
            lines.append(f"INC_VELOCITY_INIT= ({flow.velocity_m_s}, 0.0, 0.0)")
            lines.append("INC_TEMPERATURE_INIT= 288.15")
            lines.append("VISCOSITY_MODEL= CONSTANT_VISCOSITY")
            lines.append(f"MU_CONSTANT= {flow.viscosity_pa_s}")
        else:
            lines.append("SOLVER= RANS")
            lines.append("KIND_TURB_MODEL= SA")
            lines.append(f"MACH_NUMBER= {mach:.6f}")
            lines.append(f"REYNOLDS_NUMBER= {re:.1f}")
            lines.append(f"REYNOLDS_LENGTH= {ref.chord_m}")
            lines.append("FREESTREAM_TEMPERATURE= 288.15")

        lines.append(f"AOA= {flow.angle_of_attack_deg}")
        lines.append(f"SIDESLIP_ANGLE= {flow.sideslip_deg}")

        # Reference values
        lines.append("")
        lines.append("% Reference values")
        lines.append("REF_ORIGIN_MOMENT_X= 0.0")
        lines.append("REF_ORIGIN_MOMENT_Y= 0.0")
        lines.append("REF_ORIGIN_MOMENT_Z= 0.0")
        lines.append(f"REF_LENGTH= {ref.chord_m if ref.chord_m > 0 else 1.0}")
        lines.append(f"REF_AREA= {ref.area_m2 if ref.area_m2 > 0 else 1.0}")

        # Boundary conditions — map mesh physical groups to SU2 markers
        lines.append("")
        lines.append("% Boundary conditions")
        wall_markers: list[str] = []
        farfield_markers: list[str] = []

        for bc in spec.boundary_conditions:
            for face in bc.faces:
                if bc.bc_type in ("wall", "fixed"):
                    wall_markers.append(face)
                elif bc.bc_type in ("farfield", "freestream"):
                    farfield_markers.append(face)

        # Default markers if none specified
        if not wall_markers:
            wall_markers = ["wall"]
        if not farfield_markers:
            farfield_markers = ["farfield"]

        lines.append(f"MARKER_HEATFLUX= ( {', '.join(wall_markers)}, 0.0 )")
        if mach < 0.3:
            lines.append(f"MARKER_FAR= ( {', '.join(farfield_markers)} )")
        else:
            lines.append(f"MARKER_FAR= ( {', '.join(farfield_markers)} )")

        lines.append(f"MARKER_MONITORING= ( {', '.join(wall_markers)} )")
        lines.append(f"MARKER_PLOTTING= ( {', '.join(wall_markers)} )")

        # Numerical settings
        lines.append("")
        lines.append("% Numerical method")
        lines.append("NUM_METHOD_GRAD= GREEN_GAUSS")
        lines.append("CFL_NUMBER= 10.0")
        lines.append("CFL_ADAPT= YES")
        lines.append("CFL_ADAPT_PARAM= ( 0.1, 2.0, 10.0, 1e10 )")
        if mach < 0.3:
            lines.append("CONV_NUM_METHOD_FLOW= FDS")
        else:
            lines.append("CONV_NUM_METHOD_FLOW= ROE")
        lines.append("MUSCL_FLOW= YES")
        lines.append("SLOPE_LIMITER_FLOW= VENKATAKRISHNAN")
        lines.append("CONV_NUM_METHOD_TURB= SCALAR_UPWIND")
        lines.append("MUSCL_TURB= NO")

        # Linear solver
        lines.append("")
        lines.append("LINEAR_SOLVER= FGMRES")
        lines.append("LINEAR_SOLVER_PREC= ILU")
        lines.append("LINEAR_SOLVER_ERROR= 1e-6")
        lines.append("LINEAR_SOLVER_ITER= 10")

        # Convergence
        lines.append("")
        lines.append("% Convergence")
        lines.append("ITER= 5000")
        lines.append("CONV_RESIDUAL_MINVAL= -8")
        lines.append("CONV_STARTITER= 10")
        lines.append("CONV_CAUCHY_ELEMS= 100")
        lines.append("CONV_CAUCHY_EPS= 1e-6")
        lines.append("CONV_FIELD= DRAG")

        # I/O
        lines.append("")
        lines.append("% I/O")
        lines.append("MESH_FILENAME= mesh.su2")
        lines.append("MESH_FORMAT= SU2")
        lines.append("SOLUTION_FILENAME= restart.dat")
        lines.append("RESTART_FILENAME= restart.dat")
        lines.append("CONV_FILENAME= history")
        lines.append("VOLUME_FILENAME= volume")
        lines.append("SURFACE_FILENAME= surface")
        lines.append("OUTPUT_FILES= (RESTART, PARAVIEW_MULTIBLOCK)")
        lines.append("HISTORY_OUTPUT= (ITER, RMS_RES, AERO_COEFF)")
        lines.append("OUTPUT_WRT_FREQ= 100")

        cfg_path.write_text("\n".join(lines) + "\n")
        return cfg_path

    def run(self, input_path: Path, work_dir: Path) -> float:
        """Run SU2_CFD solver."""
        t0 = time.monotonic()
        result = subprocess.run(
            ["SU2_CFD", input_path.name],
            cwd=str(work_dir),
            capture_output=True,
            text=True,
            timeout=600,
        )
        elapsed = time.monotonic() - t0

        if result.returncode != 0:
            log.error("SU2_CFD failed (rc=%d): %s", result.returncode, result.stderr[:500])
            raise RuntimeError(f"SU2_CFD failed (rc={result.returncode}): {result.stderr[:500]}")

        return elapsed

    def parse_results(
        self,
        work_dir: Path,
        spec: AnalysisSpec,
    ) -> FieldResult:
        """Parse SU2 history.csv for aerodynamic coefficients."""
        aero = parse_su2_history(work_dir, spec)

        # Convert AeroResult to FieldResult for compatibility
        checks = aero.checks
        fields = (
            ScalarFieldSummary(
                field_name="pressure_coefficient",
                min_val=0.0,
                max_val=0.0,
                mean_val=0.0,
                unit="Cp",
            ),
        )

        return FieldResult(
            analysis_id=aero.analysis_id,
            status=aero.status,
            safety_factor=aero.l_over_d,  # L/D as "safety factor" proxy
            max_von_mises_mpa=0.0,
            max_displacement_mm=0.0,
            checks=checks,
            scalar_fields=fields,
            solver_name="su2",
            solve_time_s=aero.solve_time_s,
        )

    def parse_aero_results(
        self,
        work_dir: Path,
        spec: AnalysisSpec,
    ) -> AeroResult:
        """Return the full AeroResult with CL/CD/L÷D."""
        return parse_su2_history(work_dir, spec)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _convert_mesh_to_su2(self, msh_path: str, su2_path: str) -> None:
        """Convert Gmsh .msh to SU2 .su2 format via meshio."""
        try:
            import meshio

            mesh = meshio.read(msh_path)
            meshio.write(su2_path, mesh, file_format="su2")
        except ImportError:
            log.warning("meshio not installed — writing stub .su2")
            Path(su2_path).write_text("% Stub — install meshio\n")
        except Exception as exc:
            log.warning("Mesh conversion to SU2 failed: %s", exc)
            Path(su2_path).write_text(f"% Mesh conversion failed: {exc}\n")

    def _extract_flow_conditions(self, spec: AnalysisSpec) -> FlowConditions:
        """Extract FlowConditions from spec boundary conditions."""
        for bc in spec.boundary_conditions:
            if bc.bc_type == "freestream":
                return FlowConditions.from_dict(bc.value)
        # Default: 15 m/s (typical drone cruise)
        return FlowConditions(velocity_m_s=15.0)

    def _extract_aero_reference(self, spec: AnalysisSpec) -> AeroReference:
        """Extract AeroReference from spec boundary conditions."""
        for bc in spec.boundary_conditions:
            if bc.bc_type == "reference":
                return AeroReference.from_dict(bc.value)
        # Default: 1 m² reference area, 0.1 m chord
        return AeroReference(area_m2=1.0, chord_m=0.1)


# ---------------------------------------------------------------------------
# Result parsing
# ---------------------------------------------------------------------------


def parse_su2_history(
    work_dir: Path,
    spec: AnalysisSpec,
) -> AeroResult:
    """Parse SU2 history.csv for final converged aerodynamic coefficients."""
    history_path = work_dir / "history.csv"

    if not history_path.exists():
        return _failed_aero_result("No history.csv found — solver may have failed")

    # Read last row of history.csv
    try:
        with open(history_path) as f:
            reader = csv.DictReader(f)
            rows = list(reader)

        if not rows:
            return _failed_aero_result("history.csv is empty")

        last = rows[-1]

        # SU2 column names vary by solver type — try common variants
        cl = _get_coeff(last, "CL", '"CL"', "CD[cl]", "Lift")
        cd = _get_coeff(last, "CD", '"CD"', "CD[cd]", "Drag")
        cs = _get_coeff(last, "CSF", '"CSF"', "CS")
        cmx = _get_coeff(last, "CMx", '"CMx"')
        cmy = _get_coeff(last, "CMy", '"CMy"')
        cmz = _get_coeff(last, "CMz", '"CMz"')

    except Exception as exc:
        return _failed_aero_result(f"Failed to parse history.csv: {exc}")

    # Compute dimensional forces
    flow = FlowConditions(velocity_m_s=15.0)  # default
    ref = AeroReference(area_m2=1.0)
    for bc in spec.boundary_conditions:
        if bc.bc_type == "freestream":
            flow = FlowConditions.from_dict(bc.value)
        elif bc.bc_type == "reference":
            ref = AeroReference.from_dict(bc.value)

    q = 0.5 * flow.density_kg_m3 * flow.velocity_m_s**2  # dynamic pressure
    lift_n = cl * q * ref.area_m2
    drag_n = cd * q * ref.area_m2
    l_over_d = cl / cd if abs(cd) > 1e-12 else 0.0

    # Build checks
    checks = _build_aero_checks(cl, cd, l_over_d, lift_n, drag_n)

    overall = CheckStatus.PASS
    for c in checks:
        if c.status == CheckStatus.FAIL:
            overall = CheckStatus.FAIL
            break
        if c.status == CheckStatus.WARN:
            overall = CheckStatus.WARN

    return AeroResult(
        analysis_id="",
        status=overall,
        cl=round(cl, 6),
        cd=round(cd, 6),
        cs=round(cs, 6),
        cmx=round(cmx, 6),
        cmy=round(cmy, 6),
        cmz=round(cmz, 6),
        l_over_d=round(l_over_d, 2),
        lift_n=round(lift_n, 4),
        drag_n=round(drag_n, 4),
        checks=tuple(checks),
        solver_name="su2",
    )


def _get_coeff(row: dict[str, str], *keys: str) -> float:
    """Try multiple column name variants to extract a coefficient."""
    for key in keys:
        # Strip whitespace from CSV column names
        for col_name, val in row.items():
            if col_name.strip().strip('"') == key.strip().strip('"'):
                try:
                    return float(val)
                except ValueError:
                    continue
    return 0.0


def _build_aero_checks(
    cl: float,
    cd: float,
    l_over_d: float,
    lift_n: float,
    drag_n: float,
) -> list[AnalysisCheck]:
    """Build aerodynamic quality checks."""
    checks: list[AnalysisCheck] = []

    # L/D ratio check
    if l_over_d < 3:
        checks.append(
            AnalysisCheck(
                name="l_over_d",
                status=CheckStatus.FAIL,
                message=f"L/D = {l_over_d:.1f} is very low (typical drone: 5-15)",
                measured=l_over_d,
                limit=5.0,
                suggestion="Reduce airframe drag or increase wing/body lift. Check for flow separation.",
            )
        )
    elif l_over_d < 5:
        checks.append(
            AnalysisCheck(
                name="l_over_d",
                status=CheckStatus.WARN,
                message=f"L/D = {l_over_d:.1f} is below typical drone range (5-15)",
                measured=l_over_d,
                limit=5.0,
                suggestion="Consider streamlining the airframe or increasing aspect ratio.",
            )
        )
    else:
        checks.append(
            AnalysisCheck(
                name="l_over_d",
                status=CheckStatus.PASS,
                message=f"L/D = {l_over_d:.1f}",
                measured=l_over_d,
            )
        )

    # Drag coefficient check
    if cd > 0.1:
        checks.append(
            AnalysisCheck(
                name="drag_coefficient",
                status=CheckStatus.WARN,
                message=f"CD = {cd:.4f} is high — check for separation or bluff body drag",
                measured=cd,
                limit=0.1,
                suggestion="Streamline the geometry, add fairings, or reduce frontal area.",
            )
        )
    else:
        checks.append(
            AnalysisCheck(
                name="drag_coefficient",
                status=CheckStatus.PASS,
                message=f"CD = {cd:.4f}",
                measured=cd,
            )
        )

    # Negative lift check (for multicopter bodies, small negative is OK)
    if cl < -0.5:
        checks.append(
            AnalysisCheck(
                name="lift_coefficient",
                status=CheckStatus.WARN,
                message=f"CL = {cl:.4f} — significant downforce",
                measured=cl,
                suggestion="Check angle of attack and body orientation.",
            )
        )
    else:
        checks.append(
            AnalysisCheck(
                name="lift_coefficient",
                status=CheckStatus.PASS,
                message=f"CL = {cl:.4f}",
                measured=cl,
            )
        )

    return checks


def _failed_aero_result(message: str) -> AeroResult:
    return AeroResult(
        analysis_id="",
        status=CheckStatus.FAIL,
        cl=0.0,
        cd=0.0,
        cs=0.0,
        cmx=0.0,
        cmy=0.0,
        cmz=0.0,
        l_over_d=0.0,
        lift_n=0.0,
        drag_n=0.0,
        checks=(
            AnalysisCheck(
                name="solver_error",
                status=CheckStatus.FAIL,
                message=message,
                suggestion="Check solver installation and input files",
            ),
        ),
    )
