"""DUST vortex particle method solver for multi-rotor aerodynamic analysis.

DUST is an open-source unsteady aerodynamics tool using vortex particle methods.
It excels at multi-rotor wake interaction analysis — computing thrust, torque,
and efficiency for overlapping/coaxial rotor configurations at a fraction of
the cost of mesh-based CFD.

Binary: ``dust``.  Install from source:
  https://github.com/Music-and-Culture-Technology-Lab/dust

DUST uses surface panel geometry (not volume mesh), making it much faster
than RANS CFD for rotor-on-rotor interaction studies.
"""
from __future__ import annotations

import json
import logging
import math
import shutil
import subprocess
import time
from pathlib import Path
from typing import Any

from server.analysis_models import (
    AeroReference,
    AeroResult,
    AnalysisCheck,
    AnalysisSpec,
    AnalysisType,
    CheckStatus,
    FieldResult,
    FlowConditions,
    MeshInfo,
    RotorSpec,
    ScalarFieldSummary,
)
from server.analysis_solvers import FieldSolver

log = logging.getLogger("solidmind.solver_dust")


class DUSTSolver(FieldSolver):
    """DUST vortex particle method solver for multi-rotor analysis."""

    def name(self) -> str:
        return "dust"

    def analysis_types(self) -> list[AnalysisType]:
        return [AnalysisType.AERODYNAMIC]

    def available(self) -> tuple[bool, str]:
        binary = shutil.which("dust")
        if binary:
            return True, f"dust found at {binary}"
        return False, (
            "dust not found. Install from source:\n"
            "  https://github.com/Music-and-Culture-Technology-Lab/dust\n"
            "  or use SU2 for single-body aerodynamics."
        )

    def write_input(
        self,
        spec: AnalysisSpec,
        mesh_info: MeshInfo,
        work_dir: Path,
    ) -> Path:
        """Generate DUST input files.

        DUST uses a main configuration file that references geometry components
        and defines simulation parameters.
        """
        config_path = work_dir / "dust.in"

        flow = self._extract_flow_conditions(spec)
        ref = self._extract_aero_reference(spec)
        rotors = self._extract_rotors(spec)

        # Convert mesh to surface panels (STL → DUST component format)
        self._prepare_geometry(mesh_info, work_dir, spec.body)

        # Compute time stepping for unsteady analysis
        if rotors:
            max_rpm = max(r.rpm for r in rotors)
            # 10 degrees per step → 36 steps per revolution
            omega = max_rpm * 2 * math.pi / 60
            dt = (10 * math.pi / 180) / omega if omega > 0 else 0.01
            n_steps = max(360, int(2 * 360))  # 2 full revolutions
        else:
            dt = 0.01
            n_steps = 100

        lines: list[str] = []
        lines.append("! DUST configuration generated by SolidMind CAD")
        lines.append(f"! Body: {spec.body}")
        lines.append("")

        # Reference values
        lines.append("&reference_parameters")
        lines.append(f"  u_inf = {flow.velocity_m_s}")
        lines.append(f"  rho_inf = {flow.density_kg_m3}")
        lines.append(f"  a_inf = 340.3")
        lines.append(f"  mu_inf = {flow.viscosity_pa_s}")
        lines.append(f"  ref_area = {ref.area_m2 if ref.area_m2 > 0 else 1.0}")
        lines.append(f"  ref_length = {ref.chord_m if ref.chord_m > 0 else 1.0}")
        lines.append("/")
        lines.append("")

        # Freestream
        aoa_rad = math.radians(flow.angle_of_attack_deg)
        beta_rad = math.radians(flow.sideslip_deg)
        lines.append("&freestream")
        lines.append(f"  u_inf_x = {flow.velocity_m_s * math.cos(aoa_rad) * math.cos(beta_rad):.6f}")
        lines.append(f"  u_inf_y = {flow.velocity_m_s * math.sin(beta_rad):.6f}")
        lines.append(f"  u_inf_z = {flow.velocity_m_s * math.sin(aoa_rad) * math.cos(beta_rad):.6f}")
        lines.append("/")
        lines.append("")

        # Time stepping
        lines.append("&time_parameters")
        lines.append(f"  dt = {dt:.6f}")
        lines.append(f"  n_timesteps = {n_steps}")
        lines.append(f"  start_output = {n_steps // 2}")  # skip transient
        lines.append("/")
        lines.append("")

        # Wake parameters
        lines.append("&wake_parameters")
        lines.append("  n_wake_panels = 50")
        lines.append("  wake_free_length = 5.0")
        lines.append("  vortex_rad = 0.02")
        lines.append("/")
        lines.append("")

        # Components — airframe body
        lines.append("&component")
        lines.append(f"  comp_name = '{spec.body}'")
        lines.append(f"  geo_file = 'body.stl'")
        lines.append("  comp_type = 'surface_panel'")
        lines.append("  trailing_edge = .false.")
        lines.append("/")
        lines.append("")

        # Rotor components
        for rotor in rotors:
            omega_rad_s = rotor.rpm * 2 * math.pi / 60
            cx, cy, cz = rotor.center_xyz
            ax, ay, az = rotor.axis
            lines.append("&component")
            lines.append(f"  comp_name = '{rotor.rotor_id}'")
            lines.append(f"  comp_type = 'lifting_line_rotor'")
            lines.append(f"  n_blades = {rotor.num_blades}")
            lines.append(f"  radius = {rotor.radius_m}")
            lines.append(f"  omega = {omega_rad_s:.4f}")
            lines.append(f"  hub_center = {cx}, {cy}, {cz}")
            lines.append(f"  rotation_axis = {ax}, {ay}, {az}")
            lines.append(f"  collective = {rotor.collective_deg}")
            if rotor.chord_m > 0:
                lines.append(f"  chord = {rotor.chord_m}")
            lines.append("/")
            lines.append("")

        # Output
        lines.append("&output")
        lines.append("  output_forces = .true.")
        lines.append("  output_moments = .true.")
        lines.append("  output_format = 'csv'")
        lines.append("  output_dir = 'results'")
        lines.append("/")

        config_path.write_text("\n".join(lines) + "\n")
        return config_path

    def run(self, input_path: Path, work_dir: Path) -> float:
        """Run DUST solver."""
        # Create results directory
        (work_dir / "results").mkdir(exist_ok=True)

        t0 = time.monotonic()
        result = subprocess.run(
            ["dust", input_path.name],
            cwd=str(work_dir),
            capture_output=True,
            text=True,
            timeout=600,
        )
        elapsed = time.monotonic() - t0

        if result.returncode != 0:
            log.error("dust failed (rc=%d): %s", result.returncode, result.stderr[:500])
            raise RuntimeError(
                f"DUST failed (rc={result.returncode}): {result.stderr[:500]}"
            )

        return elapsed

    def parse_results(
        self,
        work_dir: Path,
        spec: AnalysisSpec,
    ) -> FieldResult:
        """Parse DUST output for aerodynamic forces per component."""
        aero = parse_dust_results(work_dir, spec)

        return FieldResult(
            analysis_id=aero.analysis_id,
            status=aero.status,
            safety_factor=aero.l_over_d,
            max_von_mises_mpa=0.0,
            max_displacement_mm=0.0,
            checks=aero.checks,
            scalar_fields=(),
            solver_name="dust",
            solve_time_s=aero.solve_time_s,
        )

    def parse_aero_results(
        self,
        work_dir: Path,
        spec: AnalysisSpec,
    ) -> AeroResult:
        """Return the full AeroResult with rotor_forces."""
        return parse_dust_results(work_dir, spec)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _prepare_geometry(
        self,
        mesh_info: MeshInfo,
        work_dir: Path,
        body_name: str,
    ) -> None:
        """Convert volume mesh to surface STL for DUST panel method."""
        try:
            import meshio
            mesh = meshio.read(mesh_info.path)
            meshio.write(str(work_dir / "body.stl"), mesh, file_format="stl")
        except ImportError:
            log.warning("meshio not installed — writing stub geometry")
            (work_dir / "body.stl").write_text("solid stub\nendsolid stub\n")
        except Exception as exc:
            log.warning("STL conversion failed: %s", exc)
            (work_dir / "body.stl").write_text("solid stub\nendsolid stub\n")

    def _extract_flow_conditions(self, spec: AnalysisSpec) -> FlowConditions:
        for bc in spec.boundary_conditions:
            if bc.bc_type == "freestream":
                return FlowConditions.from_dict(bc.value)
        return FlowConditions(velocity_m_s=0.0)  # hover by default

    def _extract_aero_reference(self, spec: AnalysisSpec) -> AeroReference:
        for bc in spec.boundary_conditions:
            if bc.bc_type == "reference":
                return AeroReference.from_dict(bc.value)
        return AeroReference(area_m2=1.0, chord_m=0.1)

    def _extract_rotors(self, spec: AnalysisSpec) -> list[RotorSpec]:
        rotors: list[RotorSpec] = []
        for bc in spec.boundary_conditions:
            if bc.bc_type == "rotor":
                rotors.append(RotorSpec.from_dict(bc.value))
        return rotors


# ---------------------------------------------------------------------------
# Mock DUST solver for testing
# ---------------------------------------------------------------------------


class MockDUSTSolver(FieldSolver):
    """Deterministic mock DUST solver for testing multi-rotor analysis."""

    def name(self) -> str:
        return "mock_dust"

    def analysis_types(self) -> list[AnalysisType]:
        return [AnalysisType.AERODYNAMIC]

    def available(self) -> tuple[bool, str]:
        return True, "mock DUST solver (always available)"

    def write_input(self, spec: AnalysisSpec, mesh_info: MeshInfo, work_dir: Path) -> Path:
        p = work_dir / "mock_dust.in"
        p.write_text("mock dust input\n")
        return p

    def run(self, input_path: Path, work_dir: Path) -> float:
        (work_dir / "results").mkdir(exist_ok=True)
        return 0.05

    def _compute_aero(self, spec: AnalysisSpec) -> AeroResult:
        """Compute deterministic mock aero result from rotor specs."""
        rotors = []
        for bc in spec.boundary_conditions:
            if bc.bc_type == "rotor":
                rotors.append(RotorSpec.from_dict(bc.value))

        rotor_forces: dict[str, dict[str, float]] = {}
        total_thrust = 0.0
        total_power = 0.0
        for rotor in rotors:
            # Simple momentum theory: T = CT * rho * A * (omega*R)^2
            area = math.pi * rotor.radius_m ** 2
            omega = rotor.rpm * 2 * math.pi / 60
            tip_speed = omega * rotor.radius_m
            rho = 1.225
            ct = 0.008  # typical
            cq = 0.0006  # typical
            thrust = ct * rho * area * tip_speed ** 2
            torque = cq * rho * area * tip_speed ** 2 * rotor.radius_m
            power = torque * omega
            total_thrust += thrust
            total_power += power
            rotor_forces[rotor.rotor_id] = {
                "thrust_n": round(thrust, 4),
                "torque_nm": round(torque, 4),
                "power_w": round(power, 4),
                "ct": ct,
                "cq": cq,
            }

        cl = 0.01  # near-zero for hover
        cd = 0.02
        l_over_d = cl / cd if cd > 0 else 0.0

        checks = _build_rotor_checks(rotor_forces, total_thrust, total_power, rotors)

        return AeroResult(
            analysis_id="mock_dust_001",
            status=checks[0].status if checks else CheckStatus.PASS,
            cl=cl, cd=cd, cs=0.0,
            cmx=0.0, cmy=0.0, cmz=0.0,
            l_over_d=round(l_over_d, 2),
            lift_n=round(total_thrust, 4),
            drag_n=0.0,
            checks=tuple(checks),
            rotor_forces=rotor_forces,
            solver_name="mock_dust",
            solve_time_s=0.05,
        )

    def parse_results(self, work_dir: Path, spec: AnalysisSpec) -> FieldResult:
        aero = self._compute_aero(spec)
        return FieldResult(
            analysis_id=aero.analysis_id,
            status=aero.status,
            safety_factor=aero.l_over_d,
            max_von_mises_mpa=0.0,
            max_displacement_mm=0.0,
            checks=aero.checks,
            scalar_fields=(),
            solver_name="mock_dust",
            solve_time_s=0.05,
        )

    def parse_aero_results(self, work_dir: Path, spec: AnalysisSpec) -> AeroResult:
        """Return the full AeroResult with rotor_forces."""
        return self._compute_aero(spec)


# ---------------------------------------------------------------------------
# Result parsing
# ---------------------------------------------------------------------------


def parse_dust_results(
    work_dir: Path,
    spec: AnalysisSpec,
) -> AeroResult:
    """Parse DUST output files for aerodynamic forces and rotor performance."""
    results_dir = work_dir / "results"

    # Look for force output files
    force_files = sorted(results_dir.glob("*forces*.csv")) if results_dir.exists() else []

    if not force_files:
        return _failed_aero_result("No force output files found in results/")

    # Parse time-averaged forces from the last portion of simulation
    total_cl = 0.0
    total_cd = 0.0
    total_lift = 0.0
    total_drag = 0.0
    rotor_forces: dict[str, dict[str, float]] = {}

    try:
        for ff in force_files:
            import csv
            with open(ff) as f:
                reader = csv.DictReader(f)
                rows = list(reader)
            if not rows:
                continue
            # Average last quarter of data (skip transient)
            n_avg = max(1, len(rows) // 4)
            last_rows = rows[-n_avg:]

            comp_name = ff.stem.replace("_forces", "").replace("forces_", "")

            # Accumulate coefficients
            for key_cl, key_cd in [("CL", "CD"), ("Cl", "Cd"), ("cl", "cd")]:
                if key_cl in last_rows[0]:
                    avg_cl = sum(float(r.get(key_cl, 0)) for r in last_rows) / n_avg
                    avg_cd = sum(float(r.get(key_cd, 0)) for r in last_rows) / n_avg
                    total_cl += avg_cl
                    total_cd += avg_cd
                    break

            # Check for rotor-specific outputs (thrust, torque)
            for key_t in ("thrust", "Thrust", "T"):
                if key_t in last_rows[0]:
                    avg_t = sum(float(r.get(key_t, 0)) for r in last_rows) / n_avg
                    avg_q = 0.0
                    for key_q in ("torque", "Torque", "Q"):
                        if key_q in last_rows[0]:
                            avg_q = sum(float(r.get(key_q, 0)) for r in last_rows) / n_avg
                            break
                    rotor_forces[comp_name] = {
                        "thrust_n": round(avg_t, 4),
                        "torque_nm": round(avg_q, 4),
                    }
                    total_lift += avg_t
                    break

    except Exception as exc:
        return _failed_aero_result(f"Failed to parse DUST results: {exc}")

    l_over_d = total_cl / total_cd if abs(total_cd) > 1e-12 else 0.0

    # Extract rotor specs for checks
    rotors = [
        RotorSpec.from_dict(bc.value)
        for bc in spec.boundary_conditions
        if bc.bc_type == "rotor"
    ]

    checks = _build_rotor_checks(
        rotor_forces, total_lift, 0.0, rotors,
    )

    overall = CheckStatus.PASS
    for c in checks:
        if c.status == CheckStatus.FAIL:
            overall = CheckStatus.FAIL
            break
        if c.status == CheckStatus.WARN:
            overall = CheckStatus.WARN

    return AeroResult(
        analysis_id="",
        status=overall,
        cl=round(total_cl, 6),
        cd=round(total_cd, 6),
        cs=0.0, cmx=0.0, cmy=0.0, cmz=0.0,
        l_over_d=round(l_over_d, 2),
        lift_n=round(total_lift, 4),
        drag_n=round(total_drag, 4),
        checks=tuple(checks),
        rotor_forces=rotor_forces,
        solver_name="dust",
    )


def _build_rotor_checks(
    rotor_forces: dict[str, dict[str, float]],
    total_thrust: float,
    total_power: float,
    rotors: list[RotorSpec],
) -> list[AnalysisCheck]:
    """Build checks for multi-rotor performance."""
    checks: list[AnalysisCheck] = []

    if not rotor_forces and not rotors:
        checks.append(AnalysisCheck(
            name="aero_result",
            status=CheckStatus.PASS,
            message="Aerodynamic analysis complete (no rotors defined)",
        ))
        return checks

    # Total thrust check
    if total_thrust > 0:
        checks.append(AnalysisCheck(
            name="total_thrust",
            status=CheckStatus.PASS,
            message=f"Total thrust: {total_thrust:.2f} N",
            measured=total_thrust,
        ))
    elif rotors:
        checks.append(AnalysisCheck(
            name="total_thrust",
            status=CheckStatus.WARN,
            message="No thrust produced — check rotor RPM and collective angle",
            measured=0.0,
            suggestion="Increase collective pitch or RPM.",
        ))

    # Per-rotor thrust balance (for multi-rotors)
    if len(rotor_forces) > 1:
        thrusts = [rf.get("thrust_n", 0) for rf in rotor_forces.values()]
        if thrusts:
            mean_t = sum(thrusts) / len(thrusts)
            if mean_t > 0:
                max_imbalance = max(abs(t - mean_t) / mean_t for t in thrusts)
                if max_imbalance > 0.15:
                    checks.append(AnalysisCheck(
                        name="thrust_balance",
                        status=CheckStatus.WARN,
                        message=f"Rotor thrust imbalance: {max_imbalance*100:.1f}% — wake interaction may be causing asymmetry",
                        measured=max_imbalance,
                        limit=0.15,
                        suggestion="Adjust rotor spacing or add tilt to reduce wake impingement.",
                    ))
                else:
                    checks.append(AnalysisCheck(
                        name="thrust_balance",
                        status=CheckStatus.PASS,
                        message=f"Rotor thrust balance: {max_imbalance*100:.1f}% imbalance",
                        measured=max_imbalance,
                    ))

    # Figure of merit (hover efficiency) for each rotor
    for rotor in rotors:
        rf = rotor_forces.get(rotor.rotor_id, {})
        thrust = rf.get("thrust_n", 0)
        power = rf.get("power_w", 0)
        if thrust > 0 and power > 0:
            # FM = T * sqrt(T / (2*rho*A)) / P
            rho = 1.225
            area = math.pi * rotor.radius_m ** 2
            p_ideal = thrust * math.sqrt(thrust / (2 * rho * area))
            fm = p_ideal / power if power > 0 else 0
            if fm < 0.5:
                checks.append(AnalysisCheck(
                    name=f"figure_of_merit_{rotor.rotor_id}",
                    status=CheckStatus.WARN,
                    message=f"Rotor {rotor.rotor_id}: FM = {fm:.3f} (poor, typical > 0.6)",
                    measured=fm,
                    limit=0.6,
                    suggestion="Optimize blade twist/chord distribution or reduce tip losses.",
                ))
            else:
                checks.append(AnalysisCheck(
                    name=f"figure_of_merit_{rotor.rotor_id}",
                    status=CheckStatus.PASS,
                    message=f"Rotor {rotor.rotor_id}: FM = {fm:.3f}",
                    measured=fm,
                ))

    return checks


def _failed_aero_result(message: str) -> AeroResult:
    return AeroResult(
        analysis_id="",
        status=CheckStatus.FAIL,
        cl=0.0, cd=0.0, cs=0.0,
        cmx=0.0, cmy=0.0, cmz=0.0,
        l_over_d=0.0,
        lift_n=0.0, drag_n=0.0,
        checks=(
            AnalysisCheck(
                name="solver_error",
                status=CheckStatus.FAIL,
                message=message,
                suggestion="Check solver installation and input files",
            ),
        ),
    )
