"""Generate Isaac Lab environment configuration from URDF analysis.

Takes a ``URDFAnalysis`` + URDF path and writes an Isaac Lab env config
Python file that can be imported by the training entry point.
"""

from __future__ import annotations

import textwrap
from pathlib import Path
from typing import Any

from server.urdf_analyzer import URDFAnalysis

# Default actuator parameters when URDF <dynamics> tags are missing.
_DEFAULT_STIFFNESS = 10.0
_DEFAULT_DAMPING = 1.0


def _observation_dim(n_joints: int) -> int:
    """Compute observation space dimensionality.

    Isaac Lab layout (no gait clock — contact sensor provides temporal signal):
    [base_lin_vel(3), base_ang_vel(3), projected_gravity(3),
     commands(3), joint_pos(N), joint_vel(N), prev_actions(N)]
    """
    return 12 + 3 * n_joints


def _build_actuator_params(analysis: URDFAnalysis) -> dict[str, Any]:
    """Build actuator stiffness/damping from URDF dynamics tags."""
    # Use first joint's damping as representative, or default
    damping = _DEFAULT_DAMPING
    stiffness = _DEFAULT_STIFFNESS
    if analysis.joint_damping:
        first_damping = next(iter(analysis.joint_damping.values()))
        if first_damping > 0:
            damping = first_damping
    # Effort-based stiffness heuristic: stiffness ~ effort / 0.1 rad
    if analysis.joint_effort:
        first_effort = next(iter(analysis.joint_effort.values()))
        if first_effort > 0:
            stiffness = first_effort / 0.1
    return {"stiffness": stiffness, "damping": damping}


def generate_env_config(
    analysis: URDFAnalysis,
    urdf_path: str | Path,
    output_path: str | Path,
    *,
    num_envs: int = 4096,
    env_spacing: float = 2.5,
) -> Path:
    """Generate an Isaac Lab environment config Python file.

    Args:
        analysis: Parsed URDF analysis.
        urdf_path: Path to the URDF file.
        output_path: Where to write the generated config .py file.
        num_envs: Number of parallel environments.
        env_spacing: Spacing between environments in meters.

    Returns:
        Path to the generated config file.
    """
    out = Path(output_path)
    urdf = Path(urdf_path).resolve()
    n_joints = len(analysis.actuated_joints)
    obs_dim = _observation_dim(n_joints)
    act_dim = n_joints
    actuator = _build_actuator_params(analysis)

    # Joint limits as lists
    lower_limits = []
    upper_limits = []
    for jname in analysis.actuated_joints:
        lo, hi = analysis.joint_limits.get(jname, (-3.14, 3.14))
        lower_limits.append(lo)
        upper_limits.append(hi)

    # Extract body dimensions from URDF link geometry if available
    body_length = getattr(analysis, "body_length_m", 0.14)
    body_width = getattr(analysis, "body_width_m", 0.15)

    # Link masses for domain randomization
    link_masses: dict[str, float] = {}
    if hasattr(analysis, "link_masses") and analysis.link_masses:
        link_masses = dict(analysis.link_masses)

    # Default joint positions: IK standing pose for hexapods, zeros otherwise.
    # For 3-DOF-per-leg hexapods (18 joints): [yaw=0, pitch=-0.52, knee=1.05] × 6
    # This corresponds to ~-30° hip pitch and ~60° knee, placing feet under the
    # body at roughly stance_height ≈ 0.14m.
    if analysis.morphology.startswith("hexapod") and n_joints == 18:
        default_positions = [0.0, -0.52, 1.05] * 6
        # Per-joint action scales: hip_yaw ±0.15, hip_pitch ±0.3, knee ±0.4
        action_scale_per_joint = [0.15, 0.3, 0.4] * 6
    else:
        default_positions = [0.0] * n_joints
        action_scale_per_joint = [0.25] * n_joints

    config_code = textwrap.dedent(f"""\
        # Auto-generated Isaac Lab environment configuration.
        # Robot: {analysis.robot_name}
        # Morphology: {analysis.morphology}
        # Generated by SolidMind CAD rl_training.env_configurator
        from __future__ import annotations

        PIPELINE = "isaaclab"

        ROBOT_NAME = {analysis.robot_name!r}
        MORPHOLOGY = {analysis.morphology!r}
        URDF_PATH = {str(urdf)!r}

        NUM_ENVS = {num_envs}
        ENV_SPACING = {env_spacing}

        # Observation / action dimensions
        NUM_JOINTS = {n_joints}
        OBS_DIM = {obs_dim}  # 12 + 3 * NUM_JOINTS
        ACTION_DIM = {act_dim}

        # Joint configuration
        JOINT_NAMES = {list(analysis.actuated_joints)!r}
        JOINT_LOWER_LIMITS = {lower_limits!r}
        JOINT_UPPER_LIMITS = {upper_limits!r}
        DEFAULT_JOINT_POSITIONS = {default_positions!r}

        # Per-joint action scales (rad)
        ACTION_SCALE_PER_JOINT = {action_scale_per_joint!r}

        # Actuator parameters
        ACTUATOR_STIFFNESS = {actuator["stiffness"]}
        ACTUATOR_DAMPING = {actuator["damping"]}

        # Robot properties
        TOTAL_MASS_KG = {analysis.total_mass_kg}
        STANDING_HEIGHT_M = {analysis.standing_height_m}
        MAX_LEG_REACH_M = {analysis.max_leg_reach_m}
        BASE_LINK = {analysis.base_link!r}
        FOOT_LINKS = {list(analysis.foot_links)!r}

        # Body dimensions (metres) for hip mount computation
        BODY_LENGTH_M = {body_length}
        BODY_WIDTH_M = {body_width}

        # Per-link masses (kg) for domain randomization
        LINK_MASSES = {link_masses!r}

        # Physics
        PHYSICS_DT = 1.0 / 200.0  # 200 Hz
        DECIMATION = 4  # control at 50 Hz
        CONTROL_DT = PHYSICS_DT * DECIMATION
    """)

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(config_code, encoding="utf-8")
    return out
