"""Generate Isaac Lab environment configuration from URDF analysis.

Takes a ``URDFAnalysis`` + URDF path and writes an Isaac Lab env config
Python file that can be imported by the training entry point.
"""
from __future__ import annotations

import textwrap
from pathlib import Path
from typing import Any

from server.urdf_analyzer import URDFAnalysis


# Default actuator parameters when URDF <dynamics> tags are missing.
_DEFAULT_STIFFNESS = 10.0
_DEFAULT_DAMPING = 1.0


def _observation_dim(n_joints: int) -> int:
    """Compute observation space dimensionality.

    Layout: [base_lin_vel(3), base_ang_vel(3), projected_gravity(3),
             commands(3), joint_pos(N), joint_vel(N), prev_actions(N)]
    """
    return 12 + 3 * n_joints


def _build_actuator_params(analysis: URDFAnalysis) -> dict[str, Any]:
    """Build actuator stiffness/damping from URDF dynamics tags."""
    # Use first joint's damping as representative, or default
    damping = _DEFAULT_DAMPING
    stiffness = _DEFAULT_STIFFNESS
    if analysis.joint_damping:
        first_damping = next(iter(analysis.joint_damping.values()))
        if first_damping > 0:
            damping = first_damping
    # Effort-based stiffness heuristic: stiffness ~ effort / 0.1 rad
    if analysis.joint_effort:
        first_effort = next(iter(analysis.joint_effort.values()))
        if first_effort > 0:
            stiffness = first_effort / 0.1
    return {"stiffness": stiffness, "damping": damping}


def generate_env_config(
    analysis: URDFAnalysis,
    urdf_path: str | Path,
    output_path: str | Path,
    *,
    num_envs: int = 4096,
    env_spacing: float = 2.5,
) -> Path:
    """Generate an Isaac Lab environment config Python file.

    Args:
        analysis: Parsed URDF analysis.
        urdf_path: Path to the URDF file.
        output_path: Where to write the generated config .py file.
        num_envs: Number of parallel environments.
        env_spacing: Spacing between environments in meters.

    Returns:
        Path to the generated config file.
    """
    out = Path(output_path)
    urdf = Path(urdf_path).resolve()
    n_joints = len(analysis.actuated_joints)
    obs_dim = _observation_dim(n_joints)
    act_dim = n_joints
    actuator = _build_actuator_params(analysis)

    # Joint limits as lists
    lower_limits = []
    upper_limits = []
    for jname in analysis.actuated_joints:
        lo, hi = analysis.joint_limits.get(jname, (-3.14, 3.14))
        lower_limits.append(lo)
        upper_limits.append(hi)

    config_code = textwrap.dedent(f"""\
        # Auto-generated Isaac Lab environment configuration.
        # Robot: {analysis.robot_name}
        # Morphology: {analysis.morphology}
        # Generated by SolidMind CAD rl_training.env_configurator
        from __future__ import annotations

        ROBOT_NAME = {analysis.robot_name!r}
        MORPHOLOGY = {analysis.morphology!r}
        URDF_PATH = {str(urdf)!r}

        NUM_ENVS = {num_envs}
        ENV_SPACING = {env_spacing}

        # Observation / action dimensions
        NUM_JOINTS = {n_joints}
        OBS_DIM = {obs_dim}  # 12 + 3 * NUM_JOINTS
        ACTION_DIM = {act_dim}

        # Joint configuration
        JOINT_NAMES = {list(analysis.actuated_joints)!r}
        JOINT_LOWER_LIMITS = {lower_limits!r}
        JOINT_UPPER_LIMITS = {upper_limits!r}

        # Actuator parameters
        ACTUATOR_STIFFNESS = {actuator['stiffness']}
        ACTUATOR_DAMPING = {actuator['damping']}

        # Robot properties
        TOTAL_MASS_KG = {analysis.total_mass_kg}
        STANDING_HEIGHT_M = {analysis.standing_height_m}
        BASE_LINK = {analysis.base_link!r}
        FOOT_LINKS = {list(analysis.foot_links)!r}

        # Physics
        PHYSICS_DT = 1.0 / 120.0  # 120 Hz
        DECIMATION = 2  # control at 60 Hz
        CONTROL_DT = PHYSICS_DT * DECIMATION
    """)

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(config_code, encoding="utf-8")
    return out
