"""Residual RL environment for Isaac Lab.

Implements a ``DirectRLEnv`` subclass where actions are residual
corrections on top of a base controller (e.g. tripod gait).  The
base controller is vectorized across all parallel environments.

This module is designed to run inside Isaac Lab's Python environment.
It imports Isaac Lab APIs at class definition time — the module can
be imported from regular Python for type checking but will fail at
runtime without Isaac Lab.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass
class ResidualEnvConfig:
    """Configuration for the residual locomotion environment.

    Populated from the generated env config file + reward config.
    """

    urdf_path: str = ""
    num_envs: int = 4096
    env_spacing: float = 2.5
    num_joints: int = 6
    obs_dim: int = 30  # 12 + 3 * num_joints
    action_dim: int = 6
    joint_names: list[str] | None = None
    joint_lower_limits: list[float] | None = None
    joint_upper_limits: list[float] | None = None
    actuator_stiffness: float = 10.0
    actuator_damping: float = 1.0
    physics_dt: float = 1.0 / 120.0
    decimation: int = 2
    residual_scale: float = 0.3
    alpha_start: float = 0.0
    alpha_end: float = 0.8
    alpha_ramp_iterations: int = 500
    # Domain randomization
    mass_randomization_pct: float = 20.0
    friction_randomization_pct: float = 30.0
    push_velocity_range: float = 0.5  # m/s
    # Base controller config (tripod gait defaults)
    base_amplitude_deg: float = 18.0
    base_stride_hz: float = 1.2


def compute_alpha(
    current_iteration: int,
    config: ResidualEnvConfig,
) -> float:
    """Compute the residual blending factor alpha.

    Ramps linearly from ``alpha_start`` to ``alpha_end`` over
    ``alpha_ramp_iterations``.
    """
    if config.alpha_ramp_iterations <= 0:
        return config.alpha_end
    t = min(1.0, current_iteration / config.alpha_ramp_iterations)
    return config.alpha_start + t * (config.alpha_end - config.alpha_start)


def build_env_config_from_file(config_path: str) -> ResidualEnvConfig:
    """Load a generated env config .py file and build ResidualEnvConfig.

    The config file is a Python module with module-level constants
    (generated by ``env_configurator.generate_env_config``).
    """
    import importlib.util
    import sys

    spec = importlib.util.spec_from_file_location("_env_cfg", config_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Cannot load env config from {config_path}")
    mod = importlib.util.module_from_spec(spec)
    sys.modules["_env_cfg"] = mod
    spec.loader.exec_module(mod)

    cfg = ResidualEnvConfig(
        urdf_path=getattr(mod, "URDF_PATH", ""),
        num_envs=getattr(mod, "NUM_ENVS", 4096),
        env_spacing=getattr(mod, "ENV_SPACING", 2.5),
        num_joints=getattr(mod, "NUM_JOINTS", 6),
        obs_dim=getattr(mod, "OBS_DIM", 30),
        action_dim=getattr(mod, "ACTION_DIM", 6),
        joint_names=getattr(mod, "JOINT_NAMES", None),
        joint_lower_limits=getattr(mod, "JOINT_LOWER_LIMITS", None),
        joint_upper_limits=getattr(mod, "JOINT_UPPER_LIMITS", None),
        actuator_stiffness=getattr(mod, "ACTUATOR_STIFFNESS", 10.0),
        actuator_damping=getattr(mod, "ACTUATOR_DAMPING", 1.0),
        physics_dt=getattr(mod, "PHYSICS_DT", 1.0 / 120.0),
        decimation=getattr(mod, "DECIMATION", 2),
    )

    # Cleanup
    sys.modules.pop("_env_cfg", None)
    return cfg
